apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpadeployment
spec:
  replicas: 2
  selector:
    matchLabels:
       app: hpapod
  template:
    metadata:
      labels:
        app: hpapod
    spec:
      containers:
      - name: paraloyalcontainer
        image: bojjavenkatesh67/paraloyal_task:latest
        ports:
        - name: http
          conatinerPort: 80
---

# service.yml
apiVersion: v1
kind: Service
metadata:
  name: hpanodeport
  labels:
    name: hpaservice
spec:
  type: NodePort
  selector:
    app: hpapod
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
